#ifndef QTSIMPLEPROGRESSDIALOG_GLOBAL_H
#define QTSIMPLEPROGRESSDIALOG_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTSIMPLEPROGRESSDIALOG_LIBRARY)
#  define QTSIMPLEPROGRESSDIALOGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTSIMPLEPROGRESSDIALOGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTSIMPLEPROGRESSDIALOG_GLOBAL_H
